### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ducky/duckster#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by ducky** [comment]
@unixorn - Cool beans. I've gone ahead and added a license. 👍

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/761
